export const skills = [
    'Android',
    'Angular',
    'Ansible',
    'ASP.NET',
    'AWS',
    'Azure',
    'C',
    'C++',
    'C#',
    'Chef',
    'Clojure',
    'Dart',
    'Django',
    'Docker',
    'Elixir',
    'Erlang',
    'Express',
    'Flask',
    'Flutter',
    'Go',
    'Google Cloud',
    'Haskell',
    'iOS',
    'Java',
    'JavaScript',
    'Kotlin',
    'Kubernetes',
    'Laravel',
    'MongoDB',
    '.NET Framework',
    'Objective-C',
    'Pearl',
    'PHP',
    'Puppet',
    'Python',
    'R',
    'React',
    'React Native',
    'Ruby on Rails',
    'Ruby',
    'Rust',
    'Scala',
    'Serverless',
    'Spring',
    'SQL',
    'Svelte',
    'Swift',
    'Terraform',
    'TypeScript',
    'Vue',
    'Xamarin'
];