export enum ProfileEditState {
    PERFORMING_NETWORK_REQUEST = 'PERFORMING_NETWORK_REQUEST',
    PROFILE_NOT_CREATED = 'PROFILE_NOT_CREATED',
    PROFILE_EDIT_READY = 'PROFILE_EDIT_READY',
    PROFILE_SAVED = 'PROFILE_SAVED',
    NETWORK_ERROR = 'NETWORK_ERROR'
}