service: skillset-infrastructure

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  searchProfiles:
    handler: src/profile/handler.search
    events:
      - http:
          path: profile/all
          method: get
          authorizer: authorise
  authorise:
    handler: src/authorisation/handler.authorise