service: skillset-infrastructure

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

functions:
  searchProfiles:
    handler: src/profile/handler.search
    events:
      - http:
          path: profile/all
          method: get
          authorizer: authorise
          cors: true
  authorise:
    handler: src/authorisation/handler.authorise

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    userProfilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userProfilesTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1