name: Acceptance_Test

on:
  workflow_run:
    workflows: [ "Deploy_Client" ]
    types:
      - completed
defaults:
  run:
    working-directory: ./acceptance

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2

      - name: Setup npm package
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: ./*
          browser: chrome
          install: true
          headless: true
          build: npm run build
          start: npm start