name: Acceptance_Test

on:
  workflow_run:
    workflows: [ "Deploy_Client" ]
    types:
      - completed
defaults:
  run:
    working-directory: ./acceptance

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2
#      - name: Setup Node.js 14
#          uses: actions/setup-node@v2
#          with:
#            node-version: '14'
#            cache: 'npm'
#            cache-dependency-path: |
#              ./client/package-lock.json
#              ./infrastructure/package-lock.json

#      - name: Run Cypress Tests
#        run: |
#          npm install
#          npm run headless-mode --browser chrome

    - name: Cypress run
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      with:
        browser: chrome
        install: true
        headless: true
#        build: npm run build
#        start: npm start


    # let's make sure our tests pass on Chrome browser
#      - name: E2E on Chrome
#      - uses: actions/checkout@v2
#      - uses: cypress-io/github-action@v2.9.7
#        with:
#          install: true
#          headless: true
#          browser: chrome
