name: SkillSet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test

#  deploy:
#    needs:
#      - build
#    name: deploy lambdas
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 14.x ]
#  steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: npm ci
#    - name: serverless deploy
#      uses: serverless/github-action@master
#      with:
#        args: deploy
#      env:
#        SERVERLESS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        # or
#        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}