name: Deploy_Production
on:
  workflow_dispatch:
    inputs: 
      version: 
        description: 'Version'
        required: true

jobs:

  test:
    name: Install Dependencies and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            ./client/package-lock.json
            ./infrastructure/package-lock.json

      - name: Build and Test Infrastructure
        working-directory: ./infrastructure
        run: |
          npm install
          npm test
      
      - name: Build and Test Client
        working-directory: ./client
        run: |
          npm install
          npm test


  deploy_infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [test]
    steps:

      # - uses: actions/checkout@v2
      # - name: Use Node.js 14
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: Deploy Lambda    
        working-directory: ./infrastructure  
        run: |
         npm install
         npm install -g serverless
         serverless deploy --stage production --region us-west-1
  
  deploy_client:
    name: Deploy Client
    env:
      S3_BUCKET_COMMAND: ${{secrets.AWS_S3_BUCKET_COMMAND_PRODUCTION}}
    runs-on: ubuntu-latest
    needs: [deploy_infrastructure]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        # uses: actions/setup-node@v2
        working-directory: ./client
        run: |
          npm install
          yarn build

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-1

      - name: S3 Deploy
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: '2.2.45'
      - run: aws s3 sync build/ $S3_BUCKET_COMMAND
        shell: bash
