name: Deploy_Client

on:
  workflow_run:
    workflows: [ "Deploy_Domain" ]
    types:
      - completed
defaults:
  run:
    working-directory: ./client

jobs:
  deploy_client:
    name: Deploy Client
    env:
      S3_BUCKET_COMMAND: ${{secrets.AWS_S3_BUCKET_COMMAND}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
      - run: |
          npm install
          yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 Deploy
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: '2.2.45'
      - run: aws s3 sync build/ $S3_BUCKET_COMMAND
        shell: bash