name: SkillSet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./infrastructure

jobs:
  build_infrastructure:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./infrastructure/package-lock.json

      - name: Build and test
        run: |
          npm install
          npm test

  deploy:
    needs:
     - build_infrastructure
    name: deploy
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./infrastructure
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - run: npm install
      - run: npm install -g serverless
      - run: serverless deploy --stage staging --region us-east-1 #${{ env.AWS_REGION }}

#      - name: serverless deploy
#        uses: serverless/github-action@v1.53.0
#        with:
#          args: deploy --package ./infrastructure
#        env:
#          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#          deploy --package path-to-folder