name: SkillSet_Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            ./client/package-lock.json
            ./infrastructure/package-lock.json

      - name: Build and Test Infrastructure
        uses: actions/setup-node@v2
        working-directory: ./infrastructure
        run: |
          npm install
          npm test
          yarn build

      - name: Build and Test Client
        uses: actions/setup-node@v2
        working-directory: ./client
        run: |
          npm install
          npm test
          yarn build

  deploy_infrastructure:
    name: Deploy Infrastructure
    defaults:
      run:
        working-directory: ./infrastructure
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: npm install
      - run: npm install -g serverless
      - run: serverless deploy --stage staging --region us-east-1

  deploy_client:
    name: Deploy Client
    defaults:
      run:
        working-directory: ./client
    needs: [build]
    env:
      S3_BUCKET_COMMAND: ${{secrets.AWS_S3_BUCKET_COMMAND}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
      - run: |
          npm install
          yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 Deploy
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: '2.2.45'
      - run: aws s3 sync build/ $S3_BUCKET_COMMAND
        shell: bash

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: [deploy_client, deploy_infrastructure]
    defaults:
      run:
        working-directory: ./acceptance
    steps:
      - name: Checkout from GH repository
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }} >> .env
      - name: Run Acceptance Test
        run: |
          npm install
          npm run headless-mode